### ISSUE TITLE
Not clear on how to start developing on this application

### ISSUE THREAD

**Issue by dstollie** [ylacaute/ez-Dashing#12]
We're curious on using this tool but it is not clear on how to start developing on this application. I see there are several options "the demo version using dockerhub", "the demo version from sources", "the production version from dockerhub" and "the production version from sources".

- What is the difference between demo and production and which one should you choose if you want to develop on the tool itself. I seems to me that the production is the one you want to use but why does the demo one even exist then?

- Also.. why should you choose the dockerhub version over the sources version.

- Lastly: I went on for the "production and build from sources" but i dont really understand the correct workflow to build the app and get it working. The steps I tried because they seemed the most logic

- install docker
- clone this project
- npm i
- ./ez.sh build-prod
- ./ez.sh start-prod /YOUR/CONFIG/DIR

but after I done that I'm getting the error that some jar kind of a jar file is missing in my build folder. Im currently not at my development PC so I can't paste the exact error. Am I missing something?

Thanks!

**Comment by ylacaute** [comment]
Hi, I agree with you, the documentation is very "light" and the _demo.sh_ is confusing. 

The demo, from source, Docker, demo.sh or whatever, is only for demonstration purpose : it shows you something working immediately. Docker just ease the process because you start the demo with one command without installing anything except Docker.

That's said, indeed, demo.sh just start the application with a mocked API. So, I will try to describe the development process below.

**Installation part :**
- install tools (npm, maven)
- clone the project
- _npm install_ inside the client

**Front development part :**
- you go on client directory
- you mock the back-end (npm run api)
- you start the live-reload (npm run dev)
Thus, you can work on JS and see a result in your browser in real time. You will probably change the mocked api because it mocks everything, including widgets. So yes, during the development you often update the json files inside the api directory.

**Backed development part :**
- you go on server directory
- as it is a Sprint Boot application which serves a REST API, there is nothing specific (mvn compile to compile, mvn package to create the fatjar, etc.)

When you have finished something important and want to check front + back (this is not always necessary) :
- stop the mocked api
- start the back-end, you will need a real dashboard.json configuration file

You can still work with this configuration if you prefer. But changing the mocked API is a way faster when you work only on JS :)

When you have finished your development and want to "package" the application for a real use, you will have to build it for production, that's means :
- create a front _dist_ directory with _npm run prod_
- copy this _dist_ directory to the Spring Boot resources directory
- do a _mvn package_ to create a fatjar with everything inside

As the process is painful : you can do it with **ez.sh build-prod**
The generated jar is your application and you will have to start it with some options, please check the startProduction section in ez.sh for that.

If you don't want Docker, you will probably have to create a simple starter.sh to run the app (java -jar ...).

Hope this will help you

**Comment by ylacaute** [comment]
@dstollie I need your feedback :) As this application is very young, your feedback is very important for me and will help me prioritize the next actions.

**Comment by dstollie** [comment]
Wow thanks for your quick response.

Im currently not in the situation where I can test it but I will try to give you feedback on the proces!. 

One part I dont really understand is why the backend api is build in Java instead of Javascript. The users of this app are probably already known with javascript (since its fully used in the frontend). Why didnt you choose a javascript solution for the backend?

One additional question: In our case we want the dashboard.json to populate from a backend dynamically. Is it possible to modify the dashboard.json realtime and update the screen with it?

**Comment by ylacaute** [comment]
You absolutely right, a Java backend is not the best solution. I first started this application with a java backend for faster development, by using different jar client (Jenkins, Sonar, etc). That allowed me to quickly start the project. As you can see now, there are no more client and the java backend is very light.

In the futur, I think it could be a good idea to replace this Java backend with a JS backend.

For your last point, it is currently not possible. At the moment, I planned to do a little improvement : if you change the dashboard.json, and do a refresh in the broswer, the application should reload the new dashboardJ;json. Currently we have to restart the server each time the configuration is changed.

What you suggest is a little bit more complicated and bring new questions : do we really want to listen a dashboard.json file or should the backend provide an API to update the file AND the front in the same time ? In your case, instead of populating the config file, you would just call a the backend api for each changes. Working with API is always better, dashboard format file is like "private" to the application :)
